=== bilaluplogic/core/tests/modwizard/modwizard.dtd
<!-- ========================================================================

    XARAYA MODULE WIZARD - DTD

-->

<!-- the root element -->
<!ELEMENT xaraya_module (
    about
    ,registry
    ,configuration
    ,database
    ,blocks
    )>

<!--

    ABOUT SECTION

-->
<!ELEMENT about ( name, copyright, license, author, description )>
<!ELEMENT name ( #PCDATA )>
<!ELEMENT copyright ( #PCDATA )>
<!ELEMENT license   ( #PCDATA )>
<!ELEMENT author    ( name, email )>
<!ELEMENT email    ( #PCDATA )>

<!ELEMENT description ( short, long )>
    <!ELEMENT short ( #PCDATA )>
    <!ELEMENT long ( #PCDATA )>

<!--

    XARAYA.ORG REGISTRY SECTION

-->
<!ELEMENT registry ( id | name )* >
<!ELEMENT id ( #PCDATA )>

<!--

    DATABASE SECTION
    ================

    Is not necessary to fill something in here.

-->
<!ELEMENT database ( table )* >

<!ELEMENT table ( label, labelfields, structure, order?, index* )* >
<!ATTLIST table
    name        CDATA #REQUIRED
    itemtype    CDATA #REQUIRED
    admin       ( true | false ) 'true'
    user        ( true | false ) 'true'
    hooks       ( enable | disable ) 'disable' >

<!ELEMENT label ( #PCDATA )>
<!ELEMENT labelfields    ( field+ )>
<!ATTLIST labelfields
     separator  CDATA '|' >
<!ELEMENT order ( field+ )>

<!ELEMENT structure ( field )*>

<!ELEMENT field ( dd_type?, dd_validation?, label? )>
<!--

    type   => from xarDB

-->
<!ATTLIST field
     name        CDATA #REQUIRED
     type        ( integer | char | varchar | text | blob | boolean | datetime | date | float | timestamp ) #IMPLIED
     size        CDATA #IMPLIED
     notnull     ( true | false ) 'false'
     primary_key ( true | false ) 'false'
     width       CDATA #IMPLIED
     decimals    CDATA #IMPLIED
     default     CDATA #IMPLIED
     increment   ( true | false ) 'false'
     overview    ( true | false ) 'true'
     unsigned    ( true | false ) 'false' >

<!ELEMENT dd_type       ( #PCDATA )>
<!ELEMENT dd_validation ( #PCDATA )>

    <!ELEMENT index ( comment?, field+ )>
    <!ATTLIST index
        name    CDATA #REQUIRED
        unique  ( true |  false ) "true" >

    <!ELEMENT comment ( #PCDATA ) >

<!--

    CONFIGURATION SECTION

-->
<!ELEMENT configuration ( capabilities, modvars, hooks, security )>

<!ELEMENT capabilities ( supportshorturls, setpagetitle )* >
<!ELEMENT supportshorturls ( #PCDATA )>
<!ELEMENT setpagetitle ( #PCDATA )>


<!ELEMENT modvars ( var )*>

<!ELEMENT var ( #PCDATA )>
<!ATTLIST var
    type CDATA  #REQUIRED
    name CDATA  #REQUIRED >


<!ELEMENT hooks ( hook )* >
<!ATTLIST hooks
    enable   ( true | false ) 'false'>

<!ELEMENT hook EMPTY>
<!ATTLIST hook
    module      CDATA #REQUIRED
    require     ( yes | no ) 'no' >

<!ELEMENT security ( component )*>
<!ELEMENT component ( query+, mask+ )+>
<!ATTLIST component
    name CDATA #REQUIRED >

<!ELEMENT query ( header, select, limit? )>
<!ELEMENT header ( #PCDATA )>
<!ELEMENT select ( #PCDATA )>
<!ELEMENT limit ( #PCDATA )>

<!ELEMENT mask (  instance, level, comment )>
<!ATTLIST mask
    name CDATA #REQUIRED >
<!ELEMENT instance ( #PCDATA )>
<!ELEMENT level ( #PCDATA )>


<!ELEMENT blocks ( block* )>
<!ELEMENT block ( #PCDATA ) >
<!ATTLIST block
    name CDATA #REQUIRED >

=== bilaluplogic/core/tests/modwizard/minimal.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- vim: tw=0
-->
<!DOCTYPE xaraya_module SYSTEM "./modwizard.dtd">

<xaraya_module>

    <!-- ABOUT

        Information about you and your module

    -->
    <about>

        <name>Wizard ( Minimal )</name>
        <copyright>by Michael Jansen</copyright>
        <license>GPL (http://www.gnu.org/licenses/gpl.html)</license>

        <author>
            <name>Michael Jansen</name>
            <email>module-wizard@michael-jansen.biz</email>
        </author>


        <description>

            <!-- add a short ONE LINE description -->
            <short>Test Module for the Module Wizard</short>
            <!-- add a description as long and detailed as you want. -->
            <long>
            * Just a silly test to check out if the wizard works.
            * </long>
        </description>

    </about>

    <!-- MODULE REGISTRY

        insert the appropriate values you got from the module registry at
        http://www.xaraya.org

    -->
    <registry>

        <id>5635</id>
        <name>wizardminimal</name>

    </registry>

    <!-- MODULE CONFIGURATION related stuff -->
    <configuration>

        <!-- CAPABILITIES OF THE MODULE

        -->
        <capabilities>

            <!-- Add code for short url-support? -->
            <supportshorturls>yes</supportshorturls>

            <!-- Add code to change <head> -> <title> tag for each page? -->
            <setpagetitle>yes</setpagetitle>

        </capabilities>


        <!-- MODULE VARIABLES

            * create and initialize / remove in xarinit
            * create a default admin_configuration possibility ??

        -->
        <modvars>
            <!--
            <var type="number" name="MembersPerPage">0</var>
            -->
        </modvars>

        <!-- HOOKS

            You have different options here:

                The enable attribute controls the generation of the hook
                calls. These calls are only generated if you say enable="yes" !

                Inside you can list module which should be hooked during
                module initialization.

        -->
        <hooks />

        <!-- SECURITY related stuff ( ROLES / PRIVILEGES )

            Create / remove Instances and Masks during initialization / removing

                The appropriate calls have to be inserted manually

            MODULE Level Instance and Masks for Blocks and Itemtypes will be created automatically and used to
            provide basic access control.
        -->
        <security>

            <!-- I have no usage for these. Perhaps they should be removed. -->
            <!--
            <component name="block">
                <query>
                    <header>Block ID</header>
                    <select>select * from block</select>
                    <limit>10</limit>
                </query>

                <query>
                    <header>Block Cat</header>
                    <select>select * from block</select>
                </query>

                <mask name="ViewMask">
                    <instance>all</instance>
                    <level>ACCESS_OVERVIEW</level>
                    <comment>A description</comment>
                </mask>

                <mask name="AdminMask">
                    <instance>all</instance>
                    <level>ACCESS_ADMIN</level>
                    <comment>A description</comment>
                </mask>
            </component>
            -->

        </security>

    </configuration>

    <!-- DATABASE related stuff -->
    <database />

    <!-- BLOCKS

        stub functions and privileges will be generated
    -->
    <blocks />

</xaraya_module>

=== bilaluplogic/core/tests/modwizard/transform.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- vim: tw=0
-->
<!DOCTYPE xaraya_module SYSTEM "./modwizard.dtd">

<xaraya_module>

    <!-- ABOUT

        Information about you and your module

    -->
    <about>

        <name>ModWizard Example - Transform</name>
        <copyright>by Michael Jansen</copyright>
        <license>GPL (http://www.gnu.org/licenses/gpl.html)</license>

        <author>
            <name>Michael Jansen</name>
            <email>module-wizard@michael-jansen.biz</email>
        </author>


        <description>

            <!-- add a short ONE LINE description -->
            <short>Module Wizard Test Module III</short>
            <!-- add a description as long and detailed as you want. -->
            <long>
            * A transform module
            *   # no tables
            *   # no blocks
            *   # doesn't use hooks
            *   # provide transform hook
            * </long>
        </description>

    </about>

    <!-- MODULE REGISTRY

        insert the appropriate values you got from the module registry at
        http://www.xaraya.org

    -->
    <registry>

        <id>5648883</id>
        <name>modwizard_transform</name>

    </registry>

    <!-- MODULE CONFIGURATION related stuff -->
    <configuration>

        <!-- CAPABILITIES OF THE MODULE

        -->
        <capabilities>

            <!-- Add code for short url-support? -->
            <supportshorturls>yes</supportshorturls>

            <!-- Add code to change <head> -> <title> tag for each page? -->
            <setpagetitle>yes</setpagetitle>

            <!-- Code for hooks ?

                 module hooks are generated if either transform_hooks or item_hooks are generated
            -->
            <item_hooks>no</item_hooks>
            <transform_hooks>yes</transform_hooks>

        </capabilities>


        <!-- MODULE VARIABLES

            * create and initialize / remove in xarinit
            * create a default admin_configuration possibility ??

        -->
        <modvars>
            <!--
            <var type="number" name="MembersPerPage">0</var>
            -->
        </modvars>

        <!-- HOOKS

            You have different options here:

                The enable attribute controls the generation of the hook
                calls. These calls are only generated if you say enable="yes" !

                Inside you can list module which should be hooked during
                module initialization.

        -->
        <hooks />

        <!-- SECURITY related stuff ( ROLES / PRIVILEGES ) -->
        <security />

    </configuration>

    <!-- DATABASE related stuff -->
    <database />

    <!-- BLOCKS -->
    <blocks />

</xaraya_module>
